// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/yseto/podcaster/ent/feeds"
)

// FeedsCreate is the builder for creating a Feeds entity.
type FeedsCreate struct {
	config
	mutation *FeedsMutation
	hooks    []Hook
}

// SetTitle sets the "title" field.
func (fc *FeedsCreate) SetTitle(s string) *FeedsCreate {
	fc.mutation.SetTitle(s)
	return fc
}

// SetURL sets the "url" field.
func (fc *FeedsCreate) SetURL(s string) *FeedsCreate {
	fc.mutation.SetURL(s)
	return fc
}

// Mutation returns the FeedsMutation object of the builder.
func (fc *FeedsCreate) Mutation() *FeedsMutation {
	return fc.mutation
}

// Save creates the Feeds in the database.
func (fc *FeedsCreate) Save(ctx context.Context) (*Feeds, error) {
	return withHooks(ctx, fc.sqlSave, fc.mutation, fc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (fc *FeedsCreate) SaveX(ctx context.Context) *Feeds {
	v, err := fc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fc *FeedsCreate) Exec(ctx context.Context) error {
	_, err := fc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fc *FeedsCreate) ExecX(ctx context.Context) {
	if err := fc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fc *FeedsCreate) check() error {
	if _, ok := fc.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Feeds.title"`)}
	}
	if _, ok := fc.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Feeds.url"`)}
	}
	return nil
}

func (fc *FeedsCreate) sqlSave(ctx context.Context) (*Feeds, error) {
	if err := fc.check(); err != nil {
		return nil, err
	}
	_node, _spec := fc.createSpec()
	if err := sqlgraph.CreateNode(ctx, fc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	fc.mutation.id = &_node.ID
	fc.mutation.done = true
	return _node, nil
}

func (fc *FeedsCreate) createSpec() (*Feeds, *sqlgraph.CreateSpec) {
	var (
		_node = &Feeds{config: fc.config}
		_spec = sqlgraph.NewCreateSpec(feeds.Table, sqlgraph.NewFieldSpec(feeds.FieldID, field.TypeInt))
	)
	if value, ok := fc.mutation.Title(); ok {
		_spec.SetField(feeds.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := fc.mutation.URL(); ok {
		_spec.SetField(feeds.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	return _node, _spec
}

// FeedsCreateBulk is the builder for creating many Feeds entities in bulk.
type FeedsCreateBulk struct {
	config
	err      error
	builders []*FeedsCreate
}

// Save creates the Feeds entities in the database.
func (fcb *FeedsCreateBulk) Save(ctx context.Context) ([]*Feeds, error) {
	if fcb.err != nil {
		return nil, fcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(fcb.builders))
	nodes := make([]*Feeds, len(fcb.builders))
	mutators := make([]Mutator, len(fcb.builders))
	for i := range fcb.builders {
		func(i int, root context.Context) {
			builder := fcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FeedsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, fcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, fcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, fcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (fcb *FeedsCreateBulk) SaveX(ctx context.Context) []*Feeds {
	v, err := fcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fcb *FeedsCreateBulk) Exec(ctx context.Context) error {
	_, err := fcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fcb *FeedsCreateBulk) ExecX(ctx context.Context) {
	if err := fcb.Exec(ctx); err != nil {
		panic(err)
	}
}
